language: python
python:
  - "3.5"
install:
  - pip3 install -r requirements.txt
#commands to run the tests
script:
  - pytest --cov
  - coverage
  - coverage3 report
  - coveralls
after success:
  - coveralls


